name: 'Desafio 5 - Agendamentos com Cron'

on:
  schedule:
    # Todos os dias Ã s 06:50 (UTC)
    - cron: '50 6 * * *'

    # A cada 30 minutos entre 08:00 e 18:00 (UTC)
    - cron: '0,30 8-18 * * *'

jobs:
  executar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Executar testes
        run: mvn clean test

      - name: Gerar relatÃ³rio
        run: echo "ðŸ“„ RelatÃ³rio gerado Ã s $(date -u)"
